2019-05-29 15:05:06,484 - __main__ - INFO - Start
2019-05-29 15:05:06,484 - __main__ - WARNING - Something maybe fail.
2019-05-29 15:05:06,484 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "/Users/huangchuang/PycharmProjects/python-learning/log_traceback.py", line 23, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2019-05-29 15:05:06,484 - __main__ - INFO - Finished
2019-05-29 15:05:26,721 - __main__ - INFO - Start
2019-05-29 15:05:26,721 - __main__ - WARNING - Something maybe fail.
2019-05-29 15:05:26,721 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "/Users/huangchuang/PycharmProjects/python-learning/log_traceback.py", line 23, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2019-05-29 15:05:26,721 - __main__ - INFO - Finished
2019-05-29 15:06:15,613 - __main__ - INFO - -------------------------------------------------------------------------
2019-05-29 15:06:15,614 - __main__ - INFO - Start
2019-05-29 15:06:15,614 - __main__ - WARNING - Something maybe fail.
2019-05-29 15:06:15,614 - __main__ - ERROR - Faild to get result
Traceback (most recent call last):
  File "/Users/huangchuang/PycharmProjects/python-learning/log_traceback.py", line 24, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2019-05-29 15:06:15,614 - __main__ - INFO - Finished
